title: Google Data Analytics Capstone Project

theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/FernandoCantu72/Google-Data-Analytics-Cyclistic-Case-Study/main/assets/Cyclistic%20Logo%20Design%202016.png
show_downloads: false
